---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге после добавления товаров в корзину.
  - Пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию.
implicit:
  - Пользователь не может редактировать описание товара.
